nombre = input('Ingresar Nombre: ')
apellido = input('Ingresar Apellido: ')
seccion = input('Ingresar Código-sección: ')
sede = input('Ingresar Sede: ')
#print (nombre,apellido,seccion,sede)
#print ("Nombre y Apellido:",nombre,apellido,"Código-sección:",seccion,"Sede:",sede)
#print ("Nombre:",nombre,"Apellido:",apellido,"Seccion:",seccion,"Sede:",sede)
print ()
print ("Datos ingresados")
print ("-Nombre y Apellido:",nombre,apellido)
print ("-Código-sección:",seccion)
print ("-Sede:",sede)
